### PR TITLE
Added workdir

### PR DESCRIPTION
**Pull request by MathiasRenner**
@DieterReuter Please review and Merge. My tests were OK.

### CODE REVIEW

**Comment by DieterReuter** [comment]
@MathiasRenner now it LGTM. Please test again, then it's ready to merge.

**Comment by MathiasRenner** [comment]
Error with using a relative path: 
"TypeError: path must be absolute or specify root to res.sendFile"

http://stackoverflow.com/questions/26079611/node-js-typeerror-path-must-be-absolute-or-specify-root-to-res-sendfile-failed

@DieterReuter: Indeed, it has to be a absolut path...

**Comment by MathiasRenner** [comment]
Please review and merge.

**Comment by DieterReuter** [comment]
Just tested it. Works great.

**Pull request merged**
